name: Build and deploy binary

on:
  push:
    branches: ["main"]
  
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu
    - name: Deploy with rsync
      uses: burnett01/rsync-deployments@7.0.0
      with:
        switches: -avzr
        path: target/x86_64-unknown-linux-gnu/release/mudlarking-server
        remote_path: /root/mudlarking_server
        remote_host: worldenddisk.com
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_KEY }}
    